"""make company_id optional for searches

Revision ID: 73280b2ad8e1
Revises: c3bfc355fa31
Create Date: 2026-08-06 21:00:32.591465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '73280b2ad8e1'
down_revision: Union[str, None] = 'c3bfc355fa31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'source_company_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True,
               existing_comment="The user's company that triggered this lead discovery")
    op.alter_column('search_sessions', 'company_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_sessions', 'company_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('leads', 'source_company_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False,
               existing_comment="The user's company that triggered this lead discovery")
    # ### end Alembic commands ###
