"""Add auth columns

Revision ID: c3bfc355fa31
Revises: 
Create Date: 2026-08-04 20:42:15.972819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3bfc355fa31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('crm_id', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('custom_fields_json', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'password_hash')
    op.drop_column('leads', 'custom_fields_json')
    op.drop_column('leads', 'crm_id')
    op.drop_column('leads', 'last_activity_at')
    # ### end Alembic commands ###
